### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by hydrotik** [gilbox/react-track#3]
Should the image be doing something in the parallax window other than staying fixed?

**Comment by gilbox** [comment]
Yeah, it moves but it's subtle. Are you testing [the public link](http://gilbox.github.io/react-track/examples/demo/demo.html) or are you testing locally?

**Comment by hydrotik** [comment]
yep, public link above. Really don't see it moving at all:) Where the branch connects to the bottom of the box stays the same when the div is at the top of the page or the bottom while scrolling.

**Comment by hydrotik** [comment]
Just checked in Chrome and works, but not in Safari 7.1.3

**Comment by gilbox** [comment]
That makes sense. I think safari requires some css vendor prefixes but I didn't add any vendor prefixes. I accept fixes via PR ( ◠‿◠ )

**Comment by hydrotik** [comment]
So I started a PR, and ran into some issues when getting the project up. Not sure if it's my node version, etc. I also attempted to do a port of the code to Typescript, but running into issues with the decorator setup. I'm going to spend a little more time on it when I wrap up a couple more things. Not sure if that helps you though?

**Comment by gilbox** [comment]
If you paste the error I will try to help you get setup. Re: Typescript I can't really help there.

**Comment by hydrotik** [comment]
assuming npm run prepush is the correct command

``` bash
$ npm run prepush

> react-track@0.2.1 prepush /myproject/node_modules/react-track
> npm run examples-build


> react-track@0.2.1 examples-build /myproject/node_modules/react-track
> rm -rf examples/js && webpack --config examples/webpack.build.config.js

Hash: 3144181af094d1827a00
Version: webpack 1.12.9
Time: 52ms
    Asset     Size  Chunks             Chunk Names
shared.js  3.17 kB       0  [emitted]  shared.js
    + 1 hidden modules

ERROR in ./examples/demo/app.js
Module parse failed: /myproject/node_modules/react-track/examples/demo/app.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React, {Component} from 'react';
| import cx from 'classnames';
| import {Easer} from 'functional-easing';
```

**Comment by hydrotik** [comment]
Also did:

``` bash
$ npm run test

> react-track@0.2.1 test /myproject/node_modules/react-track
> jsxhint . && karma start

Error while transforming jsx in file node_modules/jsxhint/test/fixtures/test_es7exponentiation.jsx
 Error: Parse Error: Line 6: Unexpected token *=
    at throwError (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
    at throwUnexpected (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)
    at parsePrimaryExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3355:9)
    at parseLeftHandSideExpressionAllowCall (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3436:61)
    at parsePostfixExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3476:20)
    at parseUnaryExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3543:16)
    at parseBinaryExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3644:17)
    at parseConditionalExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3693:16)
    at parseAssignmentExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3932:16)
    at parseExpression (/myproject/node_modules/react-track/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3984:16)
node_modules/jsxhint/test/fixtures/test_es7exponentiation.jsx: line 6, col 4, Unexpected token *=

1 error

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! react-track@0.2.1 test: `jsxhint . && karma start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-track@0.2.1 test script 'jsxhint . && karma start'.
npm ERR! This is most likely a problem with the react-track package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jsxhint . && karma start
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-track
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /myproject/node_modules/react-track/npm-debug.log
$ 
```

**Comment by gilbox** [comment]
Ah ok. Currently there are no tests so `npm test` won't help. The only command you need is (after `npm install`)

```
npm run examples
```

Then open `http://localhost:8080`

Sorry this stuff needs some work and documentation.

**Comment by hydrotik** [comment]
No worries. Doing that gives me what seems like a loader issue:

``` bash
$ npm run examples

> react-track@0.2.1 examples /myproject/node_modules/react-track
> rm -rf examples/js && webpack-dev-server --config examples/webpack.config.js --content-base examples

http://localhost:8080/webpack-dev-server/
webpack result is served from /__build__/
content is served from /myproject/node_modules/react-track/examples
Hash: 3144181af094d1827a00
Version: webpack 1.12.9
Time: 68ms
    Asset     Size  Chunks             Chunk Names
shared.js  3.17 kB       0  [emitted]  shared.js
chunk    {0} shared.js (shared.js) 0 bytes [rendered]

ERROR in ./examples/demo/app.js
Module parse failed: /myproject/node_modules/react-track/examples/demo/app.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React, {Component} from 'react';
| import cx from 'classnames';
| import {Easer} from 'functional-easing';
webpack: bundle is now VALID.
```

**Comment by gilbox** [comment]
I wiped my `node_modules/` dir just to make sure it works for me... 

Did you `npm install` first? After you clone the repo, the following two commands are all that should be necessary:

```
npm install
npm run examples
```

**Comment by hydrotik** [comment]
yep, wiped modules folder, cleared cache, even started to upgrade to .14 and babel 6. I also started playing with the web pack config so I'm thinking that it might be something strange on my end. I will do a little digging and see if I come up with anything.

**Comment by gilbox** [comment]
dang i donno then :-/

**Comment by hydrotik** [comment]
I'm going to close this as with your update you are supporting 14 and it's just a matter of passing a prefix. I will probably skip porting the code to Typescript. I am seeing another issue, but not immediately clear where the issue is. Could be react-track or react-imation. I will open another issue here as I dig deeper. Thanks for the update!
